### ISSUE TITLE
proto file "does not reside in any import path"

### ISSUE THREAD

**Issue by horacimacias** [fullstorydev/grpcurl#108]
I've been happily using grpcurl with something like the following:

```grpcurl -plaintext -import-path ../../filter/api/services -proto myservice.proto localhost:50055 myservice.MyService/MyRPC```

and it's been working fine for me.
Today a colleague reported issues running this same line. 
After comparing versions of grpcurl, turnw out I was using:
```grpcurl dev build <no version set>```
and he was using:
```grpcurl 1.3.0```

So I _brew install grpcurl_ to get on the same _official_ version and now grpcurl complains:

_Failed to process proto source files.: my_current_absolute_path/myservice.proto does not reside in any import path_

This is failing:

```grpcurl -plaintext -import-path ../../filter/api/services -proto myservice.proto localhost:50055 myservice.MyService/MyRPC```

but this is working:

```grpcurl -plaintext -proto ../../filter/api/services/myservice.proto localhost:50055 myservice.MyService/MyRPC```

is there anything I'm doing wrong?
has anything changed around this area that would explain why previous version worked fine but current does not?

**Comment by jhump** [comment]
This was certainly introduced by [this change](https://github.com/fullstorydev/grpcurl/commit/7e4045565f050728c50c5f3cab2516c444331915#diff-9b829d8901cc136a4d4f2aa83dc6501eR61).

It was changed in the hopes of behaving more like `protoc`, so that an invocation of proto include paths and source files that works with `protoc` would also work with `grpcurl`. But `protoc` behaves correctly/intuitively for this particular case and `grpcurl` fails. So this is definitely a bug.

**Comment by horacimacias** [comment]
thanks for the fast response.

I see the fix/change is in protoreflect but no changes apparently in grpcurl; is there a new version planned for grpc or how can I get the latest to test this?
I just tried _go get/install-ing_ this again after deleting old files but it seems to be pulling the same grpcurl files

**Comment by jhump** [comment]
Sorry - I didn't mean to close this issue. Github did that automatically due to my comment in the protoreflect PR.

I still need to build a _release_ of protoreflect and then update grpcurl to use that new release. (I'll then also need a new release of grpcurl.)

If you want to try it out before I get everything release, you'd have to do so w/out Go modules, so that you can just `go get -u github.com/jhump/protoreflect` and let the grpcurl build use that. (If you are using Go modules, the grpcurl build will always use the version pinned in its `go.mod` file. To make that work, you'd have to hack up its `go.mod` a bit...)

**Comment by iamatulsingh** [comment]
I tried `grpcurl 1.8.7` and  `grpcurl dev build <no version set>` and it still throwing this error. Any solution yet?

**Comment by jhump** [comment]
@iamatulsingh, a fix was released three years ago. If you are seeing this error message, it is likely due to misuse of the `-proto` and `-import-path` flags. Please open a new issue with more details of what you are doing, including the command-line flags you are using and the directory layout of sources you are trying to use.

**Comment by iamatulsingh** [comment]
I'll open new issue regarding this. Thank you @jhump

**Comment by tvprasad** [comment]
I encountered the same issue on Windows, and here’s a workaround:

1. Download and extract the files from [this link](https://github.com/fullstorydev/grpcurl/releases/tag/v1.9.1) to a local folder.
2. Add the extracted folder to your system's PATH variable: go to **System Advanced Environment** → **System Variables** → **Path**, and include the path to the extracted folder.

Hope it helps.
