### ISSUE TITLE
JSON decoding is done using encoding/json, not jsonpb

### ISSUE THREAD

**Issue by peter-edge** [fullstorydev/grpcurl#11]
This is not the general standard for Protobuf JSON https://developers.google.com/protocol-buffers/docs/proto3#json, jsonpb should be used instead. This will affect inputs such as Well-Known Types.

This can be accomplished via protoreflect, however jsonpb does not have a `json.Decoder` equivalent, you'll have to have semantics to denote the splitting of messages (perhaps just a newline). https://godoc.org/github.com/fullstorydev/grpcurl#RequestMessageSupplier should also return `[]byte` instead of `json.RawMessage` to not bind the API to the `encoding/json` package.

**Comment by peter-edge** [comment]
Note I think in practice this might be just fine, as in the end you use jsonpb in the base package, but the semantics might get extremely weird with using `encoding/json.Decoder`.

**Comment by jhump** [comment]
I'm okay with the pull request (#12), to remove this from the package's exported API.

But I don't see any value in reinventing what `json.Decoder` does or trying to come up with alternate stream encoding for multiple JSON messages in one stream. Since it is only used with `json.RawMessage`, it is fine and does exactly what we want it to -- to grab the bytes for the next JSON object in the stream.

Also worth noting that, contrary to the issue description, this tool does *not* use `encoding/json` for actual marshaling/unmarshaling. Your PR is evidence of that, since you were able to delete the import for it in `grpcurl.go` (the one with exported API, not the `package main` one) without actually touching serialization/de-serialization code.

**Comment by peter-edge** [comment]
Yep I spoke too soon, I get it now. Still nice to merge #12, but I see the value. Carry on! :-)

**Comment by antoniomo** [comment]
Hi!

What about setting https://golang.org/pkg/encoding/json/#Encoder.SetEscapeHTML to `false`? Or maybe a parameter to grpcurl for this.

I think most of us use grpcurl for dev/testing (and it's awesome!) but in this context there's no use for escaping those characters.

**Comment by jhump** [comment]
@antoniomo, that setting is for `encoding/json`, but protos must be encoded/decoded using `github.com/golang/protobuf/jsonpb`.

Before an option could be added to grpcurl, it would first have to be added to that package. Currently, strings are encoded from that package by just calling [`json.Marshal`](https://github.com/golang/protobuf/blob/14aad3d5ea4c323bcd7a2137e735da24a76e814c/jsonpb/jsonpb.go#L626).

So the place to start would be to add an issue [there](https://github.com/golang/protobuf/issues/new).

**Comment by antoniomo** [comment]
Sorry you are right, I assumed it used `encoding/json` based on this issue title, my bad!
