### ISSUE TITLE
Pre-built binaries

### ISSUE THREAD

**Issue by rayjlinden** [fullstorydev/grpcurl#114]
Sure would be nice if you built pre-built binaries for linux, mac, etc. in your releases (along with checksums).  Most of the other tools in our pipeline do something like that...

**Comment by jhump** [comment]
We do:
https://github.com/fullstorydev/grpcurl/releases/tag/v1.3.1

There are no binaries for v1.3.2 because that version is for consumers that depend on the grpcurl Go module (either building from source or linking packages from this repo into their project). It did not impact the actual built binaries, so it did not include any binaries.

I updated the 1.3.2 release notes to make this more clear. Sorry for the confusion.

**Comment by rayjlinden** [comment]
Omg.  Can’t believe I missed that.  Sorry!

But also happy!  :)
