### ISSUE TITLE
How to install grpcurl  in Centos7

### ISSUE THREAD

**Issue by mullerhai** [fullstorydev/grpcurl#119]

**Comment by jhump** [comment]
Release binaries are included in each release:
https://github.com/fullstorydev/grpcurl/releases/tag/v1.3.1

You can download them, unzip them, and then copy the files in your `PATH`. They do not require any installation steps or installing of dependencies since the executables are statically linked (like all Go binaries).

**Comment by jhump** [comment]
@mullerhai, I'm closing this issue since I haven't heard anything back. If you have more questions you can add them to this issue and we can maybe re-open if warranted.
