### ISSUE TITLE
TLS requests are made over http not https

### ISSUE THREAD

**Issue by omatsko** [fullstorydev/grpcurl#129]
I'm not sure if I understand this correctly, but making secure requests with certificate provided seems to make a request over http.

Call:
`grpcurl -cert certs\rootCA.pem -key certs\rootCA-key.pem -proto services\protos\MyService.proto -H "service: auth" -d "{\"Username\": \"test\", \"Password\": \"123\"}" grpc.local.dev:443 MyService.Signup`

Renders the following on the reverse proxy:
```
':method', 'POST'
':scheme', 'http'
':path', '/MyService/Signup'
':authority', 'grpc.local.dev:443'
'content-type', 'application/grpc' 
'user-agent', 'grpc-go/1.20.0-dev'
'te', 'trailers'
'service', 'auth'
```

This seems to be grpcurl problem as C# client sends request with the correct :scheme.

Please advice if I could overcome this somehow or if a fix is needed.

**Comment by jhump** [comment]
Hi @omatsko. Never fear, the requests are made using TLS and HTTPS. In fact, the request would not work otherwise: your server on port 443, if it expects a TLS connection, will not serve a non-TLS connection.

But, this is a bug in grpcurl. The way that the underlying Go library for gRPC decides what scheme to pass is whether or not the code has provided transport credentials. But grpcurl does not provide such credentials -- it instead uses a custom `Dialer` to do the TLS handshake step. That causes the underlying gRPC client library to _think_ the scheme is plaintext http. The custom `Dialer` was to provide better information to the user since, otherwise, the errors returned for dial failures caused by TLS handshake issues are unhelpful and confusing.

However, I am pretty certain the custom TLS handshaking could be formulated another way which would allow both the right (e.g. good) error messages to be shown to the user _and_ to make sure the underlying library realizes the scheme is https, not http.

**Comment by omatsko** [comment]
@jhump Thank you for the prompt and informative reply. I am no expert in golang or grpc-go, but if you throw some ideas at me i might try to implement a solution. :)

**Comment by jhump** [comment]
@omatsko, sorry if you wanted to cutted your teeth on implementing a fix. I already put together a patch: #130.

Before I merge that, I still want to add some tests to actually inspect the ":scheme" header.

But if you also want to try it out, you should be able to pull down this repo and checkout the branch for that pull request.

**Comment by omatsko** [comment]
@jhump I'll try out the patch. Thank you!

**Comment by omatsko** [comment]
@jhump There is another problem not related to TLS one: `':authority', 'grpc.local.dev:443'`, the port is added to the authority header where I believe it should not. Should I open another issue for this?

**Comment by jhump** [comment]
@omatsko, regarding the authority header, that is not a bug. While the port _can_ be omitted if it's the default (such as 443), it is not required to be omitted. And, in fact, must be present if it's not the default (e.g. anything other than 80 for plaintext or 443 for TLS).

I don't follow the edits. What did "dns:///" fix?

**Comment by omatsko** [comment]
@jhump Specifying port in the address string made it appear in the _:authority_ header like mentioned above. Adding _dns:///_ to the address and removing the port makes :authority header to appear as you would expect it. Like so:

```grpcurl ... dns:///grpc.local.dev MyService.Signup```.

Makes authority header to apper like this:

```':authority', 'grpc.local.dev'```

This is not related to _grpcurl_, but to _grpc-go_.

**Comment by jhump** [comment]
But as I mentioned before, from what I can tell from RFCs/specs, it's fine for the authority header to include the port. So you shouldn't _need_ the port omitted.

Is your reverse proxy doing something funny or getting confused when the port is present?

**Comment by jhump** [comment]
Also, I'm pretty sure I can (and should) fix the `-authority` header thing for TLS connections. That actually is a side effect of the patch: it worked fine before, even with TLS.

Instead of updating the `grpcurl` documentation for the `-authority` flag to suggest it only works with `-plaintext`, I'll fix it. (Otherwise, it means this patch introduces a breaking/backwards-incompatible change, for anyone that previously used that flag in conjunction with a TLS connection.)

**Comment by omatsko** [comment]
Fixing the authority cmd argument makes total sense.

We use _Envoy/Gloo_ as a reverse proxy, it routes based on host/authority header. If there is something present in the host header and you don't consider it in your route transformations, routing will not work.

**Comment by jhump** [comment]
BTW, instead of that weird `dns:///` trick, I think you can just use `-servername`.

And, unfortunately, it's not really that feasible to support `-authority` with TLS _and also_ support `-servername`. The only way I can make it respect `-authority` for TLS transactions is to actually use that as the TLS server name.

I'm really hoping that no one is doing something crazy like specifying three different hosts between the address positional argument, the `-authority` flag, and the `-servername` flag. While do-able before this patch, it is not do-able after. (And seems like bad practice.)

**Comment by omatsko** [comment]
I could see that using three different values for flags and a host name is possible, but it indeed seems like a bad practice and a hacky approach. Could people who use -servername switch to using -insecure?
