### ISSUE TITLE
Inconsistent JSON format between reflection and explicit proto files modes

### ISSUE THREAD

**Issue by DzmitrySudnik** [fullstorydev/grpcurl#132]
When I use a reflection (not providing proto files) the output json has all field names exactly as they are spelled in the proto file I used to generate a server. In particular I'm using underscored in names. However when I specify that proto file explicitly output json has camel cased fields.
That seems like a bug, despite the mode output should be the same. And ideally has the same spelling as in proto files.

Steps to reproduce:
my test service.proto file
```
service DemoService {
    rpc Test (TestRequest) returns (TestResponse) {}
}

message TestRequest{
}

message TestResponse{
    string response_body = 1;
}
```

My server implementation (in scala, don't think that really matters since server returns protobuf, not json, but still):
```
def main(args: Array[String]): Unit = {
    val server = ServerBuilder
      .forPort(8899)
      .addService(new DemoServiceImplBase {
        override def test(request: Service.TestRequest,
                          responseObserver: StreamObserver[Service.TestResponse]): Unit = {
          responseObserver.onNext(Service.TestResponse.newBuilder().setResponseBody("test").build())
          responseObserver.onCompleted()
        }
      })
      .addService(ProtoReflectionService.newInstance())
      .build()
      .start()
    
    server.awaitTermination()
}
```

Calling grpcurl without -proto:
```
> grpcurl -plaintext  "127.0.0.1:8899" "DemoService/Test"
{
  "response_body": "test"
}
```

With -proto:
```
> grpcurl -plaintext -proto service.proto  "127.0.0.1:8899" "DemoService/Test" 
{
  "responseBody": "test"
}
```

**Comment by jhump** [comment]
@DzmitrySudnik, that is very interesting. And this, under the hood, is using the standard Java protobuf runtime?

> And ideally has the same spelling as in proto files.

That is not ideal as that is not how the JSON form of protobufs is specified. According to [the spec](https://developers.google.com/protocol-buffers/docs/proto3#json), `grpcurl` is doing the right thing when looking directly at the proto sources:

> Message field names are mapped to lowerCamelCase and become JSON object keys. If the `json_name` field option is specified, the specified value will be used as the key instead. Parsers accept both the lowerCamelCase name (or the one specified by the `json_name` option) and the original proto field name.

The only reason it would behave differently with server-provided descriptors were if the descriptors provided by your server _omitted_ the `json_name` attribute (which is supposed to be always set [per the docs](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.proto#L208)).

So I think this could actually be a bug in the Java/Scala implementation of the reflection service, that it is providing incomplete descriptors to clients. But it could also be fixed in `grpcurl`, by reproducing the camel-case computation if it gets a descriptor that does not have a `json_name` value.

**Comment by DzmitrySudnik** [comment]
Thanks for a quick reply @jhump . Ok, if the camel case is a standard way for JSON conversion, let's stick to it.
According to the doc that you shared json_name, if it's omitted it should be "deduced from the field's name by converting it to camelCase". I'll try to figure out if I the reflection endpoint returns json_name (in that case I expect it to be "broken"/not camelCased) or not. If the latter that would be really nice if grpcurl applied the camel-case computation to provide consistent behavior between -proto and reflection modes.

**Comment by jhump** [comment]
This issue won't actually be resolved until there is a protoreflect release that gets incorporated into this repo.
