### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by giddel** [fullstorydev/grpcurl#172]
I run a gRPC server in a k8s environment. For local development I portforward the grpc port 9000 to localhost.
A short test shows it's working:
```
$ curl --http2 127.0.0.1:9000 -o -
```
That produces some binary stuff  and the portforwarding "log" shows that the requests are working:
```
kubectl port-forward <podname> 9000
Forwarding from 127.0.0.1:9000 -> 9000
Forwarding from [::1]:9000 -> 9000
Handling connection for 9000
Handling connection for 9000
...
``` 
Now I want to talk using grpcurl to my server but I get only a `connection refused` - no matter what commands I'm sending.
```
$ docker run fullstorydev/grpcurl -v -plaintext 127.0.0.1:9000 list
Failed to dial target host "127.0.0.1:9000": dial tcp 127.0.0.1:9000: connect: connection refused
```
And I wonder, the portforwarding "log" shows *no* `Handling connection for 9000` on my requests.
What I'm doing wrong?

**Comment by jhump** [comment]
Hi, @giddel.

When you tell the container to hit 127.0.0.1, that will be the _container's_ localhost interface -- not the host in which the container runs.

If you are on linux, you can add `--network=host` to the docker command line. That tells docker to use the host network interface directly, instead of a virtual network interface for the container.

You can also use the hostname `host.docker.internal` _instead of_ 127.0.0.1. That works on OS X, too (which doesn't support host networking).

```
docker run fullstorydev/grpcurl -v -plaintext host.docker.internal:9000 list
```

**Comment by giddel** [comment]
Perfect, thanks a lot. Now it works :-)
```
$ docker run --network=host fullstorydev/grpcurl -v -plaintext 127.0.0.1:9000  list
Failed to list services: server does not support the reflection API
```
