### ISSUE TITLE
Consider renaming `-insecure` ➡️  `-no-verify` and `-plaintext` ➡️  `-insecure`

### ISSUE THREAD

**Issue by kkweon** [fullstorydev/grpcurl#176]
I can see this issue has been created (#41, #126, #128 ) a few times already and it happened to me as well.
And, there could be many more who have not bothered to create an issue.

It'd be great if this could be renamed.

- `insecure` is used in gRPC as no TLS (e.g., [grpc.WithInsecure()](https://grpc.io/docs/guides/auth/#examples))
- On the other hand, `insecure` in grpcurl is actually `-no-verify`

Would you consider renaming `-insecure` to `-no-verify` and `-plaintext` to `-insecure`?

If not, this needs to be documented and visible very clearly.

I'm happy to contribute either way. Thank you.

**Comment by jhump** [comment]
As much I empathize with this appeal to make the names more intuitive, this would be a totally breaking change for existing users and scripts. If we were to support different names, they would have to be new flag names -- we could not change the meaning of an existing flag (such as `-insecure`).

FWIW, the `-insecure` name came from `curl`, where `--insecure` is an alternate form of `-k`. Admittedly, `curl` has no `plaintext` flag since it instead uses a URL scheme to indicate plaintext vs. TLS, so I do see how some confusion has come about.

At some point, I would like to improve the way the command-line interface works (but in a way that is still backwards compatible). At that point, I think the better solution is to offer more intuitive aliases for the flags as well as short names, and make sure they are prominent in the usage message. I think an alias of `no-verify` is quite appropriate for the insecure option. But we'd probably have to use something like `no-tls` as the alias for plaintext.

**Comment by kkweon** [comment]
Totally agree with that renaming would be too destructive.

Then, what about we show deprecation messages when **--insecure** and **--plaintext** are passed and make it in favor of **--no-verify** and **--no-tls** ?

**Comment by kkweon** [comment]
Ah there is also '--proxy-insecure' . maybe it's not so simple.

I will just update the README.md for better visibility.
