### ISSUE TITLE
Client terminating the connection after pausing the terminal

### ISSUE THREAD

**Issue by icarus3** [fullstorydev/grpcurl#187]
I am trying to test my server to see what happens when client takes long time to process the messages. Client is receiving data over unary stream.

To simulate this, I am executing grpcurl(v1.7.0) on one of the terminal on Ubuntu 18.

After, receiving few messages, I am simply pausing the terminal by clicking on it. My expectation is that, after a while terminal buffer will be full, and eventually grpc send buffer will get full, leading sender to throttle and block.

After unpausing the terminal, I receive few messages and then I get Code: Internal and  Message: unexpected EOF
I suspected that server is not handling throttling gracefully however, in wireshark I am seeing that the client is sending "FIN ACK" to server, essentially terminating the connection.
I tried passing -keepalive-time 2 without any luck.

I was expecting that grpcurl will just block on recv call, until I resume the processing or server gives up.
Any insights on this?

**Comment by jhump** [comment]
>  I am simply pausing the terminal by clicking on it.

I don't really know what this is supposed to do. Is the idea that the process is paused, as if via a `SIGPAUSE` signal? Or is it just that the I/O to `stdout` should block until there is capacity in terminal buffers?

What do server logs show?

> I was expecting that grpcurl will just block on recv call

What recv call -- to fetch next message from the server? If the server isn't paused, why would that block? FWIW, gRPC uses HTTP/2, which in turn uses application-level flow control under the hood. Depending on how grpcurl is paused, it may not be able to pass flow control frames to the server, which might then decide to hang up due to a protocol issue.

If you are using WireShark, it likely has a plugin to support HTTP/2 so should be able to show you all of the traffic. So you likely have better forensic data for figuring out what is happening than I do.

**Comment by icarus3** [comment]
Yes, block until there is capacity in terminal buffer 
Server only shows up: "wrote RST_STREAM stream=1 len=4 ErrCode=CANCEL"

I will investigate more through WIreShark, it doesn't appears to be a problem with grpcurl it self.
Thank you for the response

**Comment by jhump** [comment]
Hmm, that appears to suggest that it was the server that decided to cancel the stream, since it says it _wrote_ a `RST_STREAM` frame, as opposed to reading one from the client. Perhaps that was interpreted as unexpected, like a protocol error, to the gRPC client, which then closed the connection to establish a new, clean one?

I know a good bit about the protocol and am even fairly familiar with the implementation. But the implementation isn't mine: it's the standard Go gRPC runtime (https://github.com/grpc/grpc-go). And I have no idea what runtime you're using in the server.

It may be better to just write a custom test client that behaves the way you want (e.g. stops accepting response messages, causing backpressure to the server). Though you'll need to be aware of the various conventions of different runtimes. (For example, I think streams with the Java API will buffer in-memory and not apply backpressure, by default, unless you write code in your handler to interact with the stream and the flow control windows... maybe that's been fixed/improved, but it was that way at one point early on at least.)
