### ISSUE TITLE
Failed to dial target host "localhost:5700": tls: first record does not look like a TLS handshake

### ISSUE THREAD

**Issue by gkarnik05** [fullstorydev/grpcurl#200]
I'm trying to list all the grpc methods available against my Asp.Net Core 3.1 gRPC service running on localhost:5700 using the below command:
`grpcurl -H "Authorization: Bearer <oauth token>" -cacert "C:\Users\gpkar\OneDrive\Desktop\localhost.cer" -insecure localhost:5700 list -vv`

I get the below response:
Failed to dial target host "localhost:5700": tls: first record does not look like a TLS handshake
What am I missing? Is this the right way to invoke the command?

**Comment by jhump** [comment]
Use `-plaintext`, not `-insecure`. The `-insecure` flag means that TLS is still used, but that it does not bother authenticating the remote server (hence it being insecure). If no TLS is in use at all, `-plaintext` is the flag you want.

**Comment by gkarnik05** [comment]
Thank you @jhump. When I use `-plaintext` option, I get the below response. How do I resolve this?
 `Failed to dial target host "localhost:5700": context deadline exceeded`

**Comment by jhump** [comment]
> How do I resolve this?

Good question. That isn't enough info for me to help. For some reason, the client is not able to establish a healthy connection to your server. Perhaps you can enable server logging to further troubleshoot?

**Comment by gkarnik05** [comment]
Thank you @jhump. I will check the logs and continue to troubleshoot.

**Comment by murthy95** [comment]
@gkarnik333 did you manage to fix this ?

**Comment by WilhelmStein** [comment]
@gkarnik333 stumbled on the same issue 😆, perhaps you could recollect how you overcame that obstacle?

**Comment by jhump** [comment]
@murthy95, @WilhelmStein, are you running into a timeout error, or the original error about the failed TLS handshake?

The original issue (TLS handshake) was due to using the wrong flag (using `-insecure` instead of `-plaintext`). The follow-up was about a timeout. If you two are running into the same thing, can you provide more details? What timeout are you setting/how long is the connection taking before failing? Can you enable TLS-logging or listener/connection logging in the server to get any details out of the server's view of the same failed connection?

**Comment by WilhelmStein** [comment]
@jhump I actually fixed my issue. I do not recall how however 😅.

**Comment by marner2** [comment]
@jhump @WilhelmStein @murthy95 I just got done solving this issue and this was where I ended up first after Googling the error that comes up. In my case it had to do with an improper `appsettings.json` file in an ASP.NET Core project. I needed to add the following:
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*",
// Below was ADDED and fixed the (somewhat unrelated) issue
  "Kestrel": {
    "Endpoints": {
      "Http": {
        "Url": "http://localhost:5100"
      },
      "Grpc": {
        "Url": "http://localhost:5102",
        "Protocols": "Http2"
      }
    }
  }
}
```

**Comment by proahmedmansour** [comment]
This error happens when trying to connect to an HTTP (non-TLS) gRPC port using TLS.

Fix:

Use -plaintext if you're calling a non-TLS (HTTP) port:

`grpcurl -plaintext localhost:5100 list`

Or switch to the correct HTTPS port if TLS is enabled.

`grpcurl localhost:7168 list`

![Image](https://github.com/user-attachments/assets/65bbc3c6-2bd2-4aae-bba1-3a41a15e3578)
