### ISSUE TITLE
Add option for context timeout.

### ISSUE THREAD

**Issue by krasi-georgiev** [fullstorydev/grpcurl#204]
The grpc service is blocking until the provided context is canceled and returns a message but the grpcurl doesn't print the return message after ctrl+c or with `-max-time=` 
`-max-time` invokes an error and doesn't actually wait for the return message from the service.
For example:
```
func (*Server) Record(ctx context.Context, req *Empty) (*Response, error) {
	<-ctx.Done()
	&Response{ErrorType: "xxxxxxxxxx"}, nil
}
```
```
grpcurl -plaintext -max-time=1 0.0.0.0:9999 audior.Audior/Record
ERROR:
  Code: DeadlineExceeded
  Message: context deadline exceeded
```

I would expect here to see the actual response : `xxxxxxxxxx`

**Comment by jhump** [comment]
I don't quite understand the problem. I think what you are describing is all 100% expected with how deadline propagation works with gRPC.

> invokes an error and doesn't actually wait for the return message from the service

Yep, that's the idea: the timeout is how long it waits for a message from the service.

In your server code, no gRPC client will ever see your server's response. The context being cancelled means either (1) deadline exceeded (at which point the client has stopped waiting to see a response) or (2) cancelled (at which point the client has closed the stream and is not receiving anything further).

**Comment by jhump** [comment]
@krasi-georgiev, for that use case, you need to use streaming -- in particular, a client stream.

So the first request in the stream can _initiate_ the operation, and then the client can send another message on the same stream to ask the server to stop (instead of cancelling the RPC or letting it time out). The server would then create a _child_ context when it gets the initial request message and start processing in a goroutine. When it reads the "stop" message on the stream, it could cancel that child context, wait for the goroutine to terminate, and then send back the response.

**Comment by krasi-georgiev** [comment]
Ooog yeah great idea. Thanks!

**Comment by jhump** [comment]
Another way might be to have the time limit in the request and have the server automatically stop after that time (instead of using the RPC deadline).
