### ISSUE TITLE
Send image (binary data)

### ISSUE THREAD

**Issue by pitakill** [fullstorydev/grpcurl#21]
Hi there, thanks for the time spended in this awesome tool, it helps me a lot to test my microservice architecture. :-)

It is possible to send binary data to the gRPC server?

Something like curl does.

Thank you for your time :-)

**Comment by jhump** [comment]
@pitakill, You can do this with a request message that has a field of type `bytes` in the proto. In grpcurl, the field would need to be specified in base64-encoded strings since that is the spec'ed way that `bytes` fields are represented in JSON. (Here's that spec: https://developers.google.com/protocol-buffers/docs/proto3#json)

Does that answer your question?

**Comment by pitakill** [comment]
@jhump you totally rock!, yes, that answers my question. :-)

In my defense i'm pretty new to the protobuf spec, a couple of weeks of testing and building some basic stuff. :-P
