### ISSUE TITLE
Triggering a GRPC server method in ec2 docker container from local machine ?

### ISSUE THREAD

**Issue by Private-SO** [fullstorydev/grpcurl#219]
I have a simple grpc service [helloworld][1]. its server is running in ec2 instance behind nginx. I am trying to connect to grpc server from my local machine using curl. I am following the same code that is in official [repo][2] so I don't think any problem from code side because I can able to connect to my grpc server from my local grpc client ([greeter_client.py][3]). 

But when I tried with grpcurl I am getting response like this 

```
grpcurl -plaintext 3.xx.xx.xxx:50052 3.xx.xx.xx:50052.helloworld.Greeter

Error invoking method "3.xx.xxx.xxx:50052.helloworld.Greeter": rpc error: code = Unknown desc = failed to query for service descriptor "3.xx.xxx.xxx:50052.helloworld": No Content: HTTP status code 204; transport: missing content-type field
```

My nginx config:

    server {
            listen 50052 http2;
            location /helloworld {
             default_type application/grpc;
          grpc_pass grpc://localhost:50051;
            }
        # Error responses
        include conf.d/errors.grpc_conf; # gRPC-compliant error responses
        default_type application/grpc;  
    }

The grpc server is running in docker container with exposed port on `50051`.

    root@ip-xx2-x1-xx-xx:/etc/nginx/sites-enabled# docker ps
    CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                      NAMES
    xxx        xxx        "/bin/sh -c 'python …"   6 hours ago         Up 6 hours          0.0.0.0:50051->50051/tcp   obje_galois

  [1]: https://grpc.io/docs/languages/python/quickstart/
  [2]: https://github.com/grpc/grpc/tree/master/examples/python/helloworld
  [3]: https://github.com/grpc/grpc/blob/master/examples/python/helloworld/greeter_client.py

Thanks. Any help is appreciated.

**Comment by jhump** [comment]
The issue at hand is the error "failed to query for service descriptor". That is related to server reflection, which is how `grpcurl` learns about your RPC schema. There are a couple of work-arounds/solutions:

* You need to provide `grpcurl` with your proto source file, so that it understands your RPC schema. You can use a `-proto` argument to point it to the file that defines the service. If that file imports others, you may also need to use `-import-path` arguments so that all of the dependencies can be found.
* OR you can enable server reflection in your server. Then `grpcurl` can ask your server about your RPC schema. This one requires a couple of things:
    1. Enable server reflection; more details [here](https://github.com/grpc/grpc/blob/master/doc/server-reflection.md#known-implementations).
    2. Configure nginx to also proxy `/grpc.reflection.v1alpha.ServerReflection` to your server. That is the name of the reflection service, and thus the URI path that `grpcurl` will need to use.

_Next_, even after getting past the above, you'll likely encounter a problem with that method:`3.xx.xx.xx:50052.helloworld.Greeter` is not a valid method name. The method name should be the fully-qualified name of the method from the proto source. So the "3.xx.xx.xx:50052" is not part of that and must be omitted. The rest, "helloworld.Greeter", doesn't look right either -- that looks like a service named "Greeter" in the package "helloworld". It appears to be missing the actual method name. I think your nginx config may also need to be updated to proxy `/helloworld.Greeter` for this service, not just `/helloworld`. I found an [nginx blog post](https://www.nginx.com/blog/nginx-1-13-10-grpc/) with a setup that's almost identical to yours, so you may want to consult it.

**Comment by Private-SO** [comment]
Thanks so much for your detailed answer. I can able to run my first `grpcurl` request successfully.
```
grpcurl -plaintext -proto helloworld.proto 3.xx.xxx.xxx:50052 helloworld.Greeter/SayHello
{
  "message": "Hello, !"
}
```
How can i pass the variable to this request ? Right now it is expecting something like this 
`return helloworld_pb2.HelloReply(message='Hello, %s!' % request.name)`

I tried below command
```
grpcurl -plaintext -proto helloworld.proto -d '{"name":"World"}' 3.xx.xxx.xxx:50052 helloworld.Greeter/SayHello
Error invoking method "helloworld.Greeter/SayHello": error getting request data: invalid character '\'' looking for beginning of value
```
Am i missing anything ?

**Comment by jhump** [comment]
Are you using Windows? I think the command-line tool/shell in Windows is very weird with regards to quoting/escaping. The given example works for most all other shells (bash, zsh, etc... for unix-y OSs including linux and mac).

**Comment by jhump** [comment]
If you are on Windows, here's another issue where a solution is discussed, if you are using PowerShell. (Judging from that error message, I suspect you are not though): #106.

You. might also try using `-d @` and then piping the request body into `grpcurl`'s stdin. This is pretty easy with any unix-y shell, but I guess your mileage may vary if you are using Windows...

**Comment by Private-SO** [comment]
yes I am using windows. The above issue helped me in solving my problem. Thanks  👍
