### ISSUE TITLE
google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.39.0), but does not contain package google.golang.org/grpc/naming

### ISSUE THREAD

**Issue by JeremyHarisch** [fullstorydev/grpcurl#237]
As the title already says it: When running `go mod tidy` I am getting the following error:

```
 go mod tidy
go: finding module for package google.golang.org/grpc/examples/helloworld/helloworld
go: finding module for package google.golang.org/grpc/naming
go: found google.golang.org/grpc/examples/helloworld/helloworld in google.golang.org/grpc/examples v0.0.0-20210629184516-b3f274c2baba
go: finding module for package google.golang.org/grpc/naming
github.com/kyma-project/cli/cmd/kyma/provision imports
	github.com/kyma-incubator/hydroform/provision imports
	github.com/kyma-incubator/hydroform/provision/internal/azure imports
	github.com/kyma-incubator/hydroform/provision/internal/operator/terraform imports
	github.com/hashicorp/terraform/backend/init imports
	github.com/hashicorp/terraform/backend/remote-state/etcdv2 imports
	github.com/coreos/etcd/client tested by
	github.com/coreos/etcd/client.test imports
	github.com/coreos/etcd/integration imports
	github.com/coreos/etcd/proxy/grpcproxy imports
	google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.39.0), but does not contain package google.golang.org/grpc/naming
```

I already tried some different versions, as suggested in [here](https://github.com/fullstorydev/grpcui/issues/89), but I could not fix it. Could somebody guide me to solve this?

**Comment by jhump** [comment]
This seems like an issue to file in https://github.com/grpc/grpc-go? Or maybe more accurately in `github.com/coreos/etcd/proxy/grpcproxy`? This repo does not import `google.golang.org/grpc/naming`, so it must be some other dependency that references it.

I don't actually have much interest in getting this to work. The `go.mod` and `go.sum` files are adequate right now, and everything builds, so there's no need to tidy them. (The only "superfluous" rows in there are indirect dependencies for tools used by the `Makefile`, which I don't want to remove anyway.)

Also, I have issues running `go mod tidy` in _lots_ of repos because of stuff like this -- weird dependencies or configuration issues in dependencies that upset the tidy process even though the code builds fine.

In this case, I bet the issue is just that some `go.mod` file somewhere in the transitive graph of dependencies is bad and that dependency should be updated. But it's hard to find the problem just using the `go` tool. The import trace appears to pinpoint  `github.com/coreos/etcd/proxy/grpcproxy` -- which imports a package that does not exist. But it is also trying to use `@latest` for the gRPC library there, but the etcd repo now pins v1.38.0 (not "latest").

This could be a weird quirk of `go mod tidy` since I'm not even sure why the start of that import trace (`github.com/kyma-project/cli/cmd/kyma/provision`) is there. When I run `go mod why github.com/kyma-project/cli/cmd/kyma/provision`, it tells me that package is in fact _not_ needed by `grpcurl`. 🤷

**Comment by luqmansen** [comment]
Package naming was removed in v1.30.0

quick fix, add this to `go.mod`

`replace google.golang.org/grpc => google.golang.org/grpc v1.29.0
`

**Comment by davidlhoffman** [comment]
Thank you, @luqmansen!  

In my case, I had to use:
replace google.golang.org/grpc => google.golang.org/grpc v1.43.0

The version matches the one currently referenced at [https://grpc.io/docs/languages/go/quickstart/]

**Comment by davidlhoffman** [comment]
Hi, @Phil-sun, that was my solution.  I followed @luqmansen's suggestion but substituted the newest version referenced on the quickstart page.

**Comment by AdolphKevin** [comment]
grpc package version too high. 

`replace google.golang.org/grpc => google.golang.org/grpc v1.29.1`

**Comment by jhump** [comment]
@le-vlad, can you not update whatever dependency is using `google.golang.org/grpc/naming`? It was removed from the grpc-go repo over _three years ago_. So trying to pin such an old version is bound to cause problems (unless you roll back _lots_ of your dependencies to old versions).
