### ISSUE TITLE
unresolvable reference to "google.protobuf.Timestamp

### ISSUE THREAD

**Issue by lwmxiaobei** [fullstorydev/grpcurl#249]
Because grpc-js does not support reflection, so I implemented server-side reflection myself, but when I used google.protobuf.Timestamp in proto, I got an error. Here is a screenshot:

![image](https://user-images.githubusercontent.com/16284775/128822775-02175b76-a23e-4005-8a6b-0eedeb902297.png)

but when I remove google.protobuf.Timestamp it is normal
I don't know why this is，can you help me ? thinks

This is part of my proto file content：

![image](https://user-images.githubusercontent.com/16284775/128823232-f07747ff-42ae-4bfd-a72b-474935f208d0.png)
![image](https://user-images.githubusercontent.com/16284775/128823273-740091e8-6f92-46d7-9dcb-505734144238.png)

**Comment by jhump** [comment]
This would be a bug in your implementation of server reflection.

When downloading descriptors, `grpcurl` basically does the following:

1. First it issues a [`file_containing_symbol`](https://github.com/grpc/grpc/blob/master/src/proto/grpc/reflection/v1alpha/reflection.proto#L41) request for the given service name.
2. It then issues a [`file_by_filename`](https://github.com/grpc/grpc/blob/master/src/proto/grpc/reflection/v1alpha/reflection.proto#L36) request with the resulting filename. After unmarshaling the returned `google.protobuf.FileDescriptorProto`, it makes more requests for each dependency, recursively, until the entire transitive dependency graph has been downloaded.
3. At this point, it has all needed descriptors to build the reflection information needed. But this error message means that it could not locate any definition for `google.protouf.Timestamp` in all of the downloaded file descriptors.

The issue is either in the file descriptor returned for the main file, `gd_pts_afterSale.proto`, such that it does not correctly include all of its dependencies, _OR_ there is a problem in the file descriptor returned for `google/protobuf/timestamp.proto`, such that it does not correctly define this type (perhaps an issue with the declared package of the file or missing declarations?).

**Comment by lwmxiaobei** [comment]
thinks.
I loaded proto through [proto-loader.](https://github.com/grpc/grpc-node/tree/master/packages/proto-loader) google/protobuf/timestamp.proto is provided by Google, will it automatically load dependencies? My server is implemented through [proto-loader](https://github.com/grpc/grpc-node/tree/master/packages/proto-loader), and grpcurl -proto can work normally.
The following is the FileDescriptorProto I loaded through the [proto-loader](https://github.com/grpc/grpc-node/tree/master/packages/proto-loader). I am not sure whether the dependency is included. How can I confirm whether the dependency is included?

![image](https://user-images.githubusercontent.com/16284775/128959075-ab82c82b-b9c0-47ac-ae55-bae3b9d0fce3.png)

**Comment by lwmxiaobei** [comment]
![image](https://user-images.githubusercontent.com/16284775/128960574-e5b9ed3e-3eca-4c8b-9d01-06285892c7d8.png)

The first element of the fileDescriptorProtos array is gd_pts_afterSale.proto, and the second element is google_protobuf.proto. It seems that all dependencies are returned to grpcurl, but I’m not sure if I need to deal with anything else.

**Comment by lwmxiaobei** [comment]
I found the problem, need to use FileDescriptorProto.addDependency('google_protobuf.proto') to add a dependency, so that it can work
