### ISSUE TITLE
Usage Help or Feature Request: Connect to Unix Socket

### ISSUE THREAD

**Issue by dionysius** [fullstorydev/grpcurl#25]
Hi, I can't find any information about a possibility to connect to a unix socket. Can I or is this feature not available (yet)?

**Comment by jhump** [comment]
@dionysius, it was not a feature until you mentioned. #26, when merged, will add basic support.

I say "basic" support, because there are a couple of quirks to keep in mind:
1. Using the `-unix` flag with grpcurl does not change the default behavior of `-plaintext`. So, unless you are using TLS over unix domain socket (which seems like total overkill), you will need to specify both `-unix -plaintext`.
2. You can use `testserver` to test using the `-unix` flag. However, it does not try to unlink the given path before binding to it and it also does not try to unlink it on shutdown. So you likely need to manually remove the socket after the test server shuts down before trying to start it back up using the same domain socket path.

**Comment by jhump** [comment]
Resolved in #26
