### ISSUE TITLE
grpcurl not respecting -H value on CLI

### ISSUE THREAD

**Issue by timm088** [fullstorydev/grpcurl#43]
Seem to be running into some issues using grpcurl with nginx-ingress

Specifically, i run

`grpcurl -H 'content-type: application/grpc' mything.com:443 list`

And get returned
`Failed to list services: rpc error: code = Internal desc = transport: received the unexpected content-type "text/plain; charset=utf-8`

Not sure if i'm meant to then add `-reflect-header 'content-type: application/grpc' ` , but doing so gets me no fruther. 

The Service in question has TLS enabled at the service (pod) level, and it is valid using letsencrypt production certificate (I would expect a TLS error anyone on the CLI if something was wrong here?)

Any thoughts? Something i'm doing wrong to pass the header in? Tried to following the --help documentation but cant see where i'm passing the header incorrectly

**Comment by jhump** [comment]
Hi, @timm088,
The content-type I think will be ignored. The `grpcurl` program will try to add it as request metadata, but the gRPC runtime library ignores certain metadata keys, because they are [reserved](https://github.com/grpc/grpc-go/blob/master/internal/transport/http_util.go#L134): the gRPC runtime is [already adding](https://github.com/grpc/grpc-go/blob/master/internal/transport/http2_client.go#L377) appropriate `content-type` headers to the request.

The error is saying that the *server* replied with a `text/plain` response (instead of a gRPC response). I'm going to guess that is probably nginx trying to serve some error page as plain text.

A few questions & suggestions that may help:
1) Does your server support gRPC server reflection? If no, or you don't know, then chances are that the reflection calls wouldn't work anyways (even if nginx were properly configured with how to route those requests to the backend). In that case you need to use `-proto` arguments, to point `grpcurl` at your proto source files.
2) Try using `tcpdump` or Wire shark, or some other tool that can capture network activity between `grpcurl` and the server. That would let you see the full response payload that nginx is returning (which is, unfortunately, omitted from the `grpcurl` error message).
3) If nginx is only configured to route certain paths to the server (such as `/<service,name>/*`), then the reflection requests would confuse nginx. So, even if your server *does* support reflection, it could be that the requests aren't even making it to your server due to the reverse proxy config. To have the reflection calls also forwarded to your backend, make sure you have a route configured for the `/grpc.reflection.v1alpha. ServerReflection/ServerReflectionInfo` URI.

**Comment by timm088** [comment]
Interesting @jhump , really appreeciate your response.

So there is an nginx in front of this server, behind an ELB (passing tcp on port 443).
(nginx-ingress controller inside kubernetes actually)

I can see the requests get to the nginx ingress (in logs), but never to the pod itself. 

When i port-forward to remove the nginx, I have no issues with the `list` using grpcurl, so I'm guessing everything about the underyling code supports reflection.

Re 3: Nginx is configured to route the root `/` on a single hostname that is only for this particular service, so I dont think i'm having any issues there? It sounds a lot more like the requests dont make their way due to the proxy configuration, but from what I can see, everything is configured correctly on the nginx-ingress in order for this to occur ...

**Comment by jhump** [comment]
> I can see the requests get to the nginx ingress (in logs), but never to the pod itself.

I think that is pretty conclusive that there is something going on in the nginx configuration, not grpcurl.

I would try to snoop on the actual response it is sending back when you see things fail. The fact that it sends back a "text/plain" content-type suggests it is trying to send back some sort of textual error message (which might help?)
