### ISSUE TITLE
Fail to inspect custom `gRPC` server

### ISSUE THREAD

**Issue by cmgsj** [fullstorydev/grpcurl#432]
Listing available services works correctly.
```bash
$ grpcurl -plaintext localhost:9090 list    
demo.v1.DemoService
grpc.health.v1.Health
grpc.reflection.v1.ServerReflection
grpc.reflection.v1alpha.ServerReflection
```

However, describing a "custom" service fails, while the rest of the `grpc.*` services do not.
```bash
$ grpcurl -plaintext localhost:9090 describe demo.v1.DemoService                
Failed to resolve symbol "demo.v1.DemoService": proto: invalid syntax: "<unknown:0>"
```

Is this a know issue?
Should I register only either `v1` or `v1alpha` reflection services?

**Related:** https://github.com/fullstorydev/grpcui/issues/279

**Comment by jhump** [comment]
See #423. The issue is twofold:
1) Your server is written in Go, and is exhibiting these issues:
   * https://github.com/grpc/grpc-go/issues/6770
   * https://github.com/golang/protobuf/issues/1575
2) The above issues are triggered by one or more of the files in the schema you are trying to download use the wrong import path when importing a dependency. By "wrong", I mean they are using a path different than the one the file was actually compiled with (more details can be found [here](https://buf.build/docs/reference/protobuf-files-and-packages#imports)).

**Comment by cmgsj** [comment]
> See #423. The issue is twofold:
> 
> 1. Your server is written in Go, and is exhibiting these issues:
>    
>    * [reflection: if some files cannot be resolved, reflection will send invalid descriptors to client grpc/grpc-go#6770](https://github.com/grpc/grpc-go/issues/6770)
>    * [reflection/protodesc: placeholder files produce a descriptor with strange syntax value golang/protobuf#1575](https://github.com/golang/protobuf/issues/1575)
> 2. The above issues are triggered by one or more of the files in the schema you are trying to download use the wrong import path when importing a dependency. By "wrong", I mean they are using a path different than the one the file was actually compiled with (more details can be found [here](https://buf.build/docs/reference/protobuf-files-and-packages#imports)).

@jhump Thank you for the quick response 🙏
I fixed the import paths in my `proto` files based on the docs you referenced, and everything is now working as expected.

I will close this non-issue.
