### ISSUE TITLE
Cannot list methods of a service and make requests

### ISSUE THREAD

**Issue by ttc0419** [fullstorydev/grpcurl#451]
When I list services, it works as intended:
```shell
[u]% grpcurl -plaintext 127.0.0.1:5443 list
grpc.reflection.v1.ServerReflection
grpc.reflection.v1alpha.ServerReflection
xxx.yyy
```
But when I was trying to list the methods:
```shell
[u]% grpcurl -plaintext 127.0.0.1:5443 list 'xxx.yyy'
Failed to list methods for service "xxx.yyy": Symbol not found: xxx.yyy
caused by: File not found: openapi/v3/annotations.proto
```
And it cannot invoke GRPCs as well:
```shell
[u]% grpcurl -d 'some json data' -plaintext 127.0.0.1:5443 '/xxx.yyy/Get'
Error invoking method "/xxx.yyy/Get": target server does not expose service "/xxx.yyy"
```

**Comment by jhump** [comment]
You can provide the schema yourself by providing proto source files are a compiled file descriptor set (using the `-o` argument of `protoc` or using `buf build`). But the issue here is that the reflection endpoint in the server is unable to provide the entire schema. As it states, it cannot provide a file descriptor for the import `openapi/v3/annotations.proto`.

This is an issue with how the Gnostic stuff is being used. For reflection to correctly work, the path you use in an _import_ statement must match the path used when that file was compiled to generated Go code. [This comment](https://github.com/google/gnostic/issues/337#issuecomment-1998304139) suggests you should be arranging your file system structure to so that the import statement is "openapiv3/annotations.proto" (no slash between "openapi" and "v3").

I can also look at updating my [grpcreflect](https://pkg.go.dev/github.com/jhump/protoreflect/grpcreflect) package to try to be lenient about this sort of thing. Generally, all of a file's imports must be present in order to properly construct a schema model for elements in that file. However, imports that _only supply custom options_ could actually be omitted and the schema could still be constructed. The result is that any custom options would be uninterpreted, which would work for grpcurl and grpcui since they don't care about custom options (though it does mean that custom options would be absent when you try to `describe` an element with grpcurl).
