### ISSUE TITLE
ERROR: requires length-delimited wire type

### ISSUE THREAD

**Issue by HT808s** [fullstorydev/grpcurl#94]
Hello !
I looked over the internet but so far I haven't seen an error like this elsewhere.

I get this when `grpcurl` tries to decode the response of my server.
```sh
ERROR:
  Code: Internal
  Message: grpc: failed to unmarshal the received message bad input; field api.Foo.UpdateTS requires length-delimited wire type
```
This field in question is of type [google.protobuf.Timestamp](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/timestamp.proto).

Is there any chance you know what is going on and how I can fix this?

Cheers!

**Comment by jhump** [comment]
@HT808s, are you using server reflection, or are you pointing `grpcurl` at your proto source files? If the latter, maybe it is possible that your are pointing `grpcurl` at different protos than were used to build the server?

This error indicate that the server is not using the same protocol. A `google.protobuf.Timestamp` is a nested message, and message fields use the "length-delimited" wire type to encode the field value (vs. "varint", "fixed32", or "fixed64" wire types that other field types use). The server is sending back a response where that field number is encoded with one of these other wire types. This usually indicates that the server is using a different protocol than the client.

Maybe you changed the protocol from an `int64` milliseconds-since-epoch to a `google.protobuf.Timestamp`, but forgot to recompile the server?

**Comment by jhump** [comment]
If you use server reflection, problems like this should go away since you can be certain that `grpcurl` uses the same protocol as the server.

If you *are* using server reflection, can you tell us more info? Maybe share the `.proto` file that defines the service and also let me know what language/runtime the server is written in?

**Comment by HT808s** [comment]
I don't rely on reflection, I used a protoset file

**Comment by HT808s** [comment]
There was indeed a subtle difference between the proto server side and grpcurl side !
Thanks for giving me the lead on this error !
