### ISSUE TITLE
-emit-defaults is needed to show output if the output only contains default values

### ISSUE THREAD

**Issue by electrofink** [fullstorydev/grpcurl#97]
If an Unary RPC is called and the output contains only default values (explicitly set on the response), the values don't show upless I set `-emit-defaults`. This is somewhat surprising behaviour because I would expect that option only to have any effect if the values on the response are not set. However if they *are* set and just happen to match the defaults, grpcurl is not printing the response unless I set `-emit-defaults`.
If I do the same call with a client library (such as the Node.js gRPC library), the values (the number 0 in this case) are there.

**Comment by jhump** [comment]
Are you using proto2 or proto3 syntax in your proto source files?

If you are using proto3, this is expected behavior: proto3 does *not* emit default values on the wire, regardless of whether they are explicitly set or not. So `grpcurl` has no way of knowing whether they were explicitly set or implicitly left as default values. So you must use `-emit-defaults` if you want to see these values.

**Comment by electrofink** [comment]
That is right, I forgot about this implementation detail. I'm using proto3 syntax. I was just surprised to get a different result with `grpcurl` than with an official client library. I guess that library defaults to some equivalent of `-emit-defaults`. Might be useful to enable this behaviour as well in `grpcurl` but it's not a bug. Feel free to close this issue :slightly_smiling_face:
